[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@account-abstraction@v0.7.0/=lib/account-abstraction/contracts/",
]
solc = "0.8.23"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Network settings for deployment
[rpc_endpoints]
sepolia = "https://ethereum-sepolia-rpc.publicnode.com"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
